language: php

php:
  - 7.1

cache:
  composer: true
  npm: true

before_install:
  - phpenv config-add project-base/docker/php-fpm/php-ini-overrides.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-rm xdebug.ini || return 0
  - composer global require hirak/prestissimo

install:
  - composer install --optimize-autoloader --no-interaction --no-progress
  - php phing npm

script:
  - php phing standards
  - php phing tests-static
